#!/usr/bin/with-contenv bash

# Check if /etc/nginx/ssl exists
if [ ! -d "/etc/ssl/nginx" ]; then
	mkdir -p "/etc/ssl/nginx"
fi

# Generate Diffie-Hellman parameters
if [ ! -f "/etc/ssl/nginx/dh2048.pem" ]; then
	echo "Generating Diffie-Hellman parameters..."
	openssl dhparam -out "/etc/ssl/nginx/dh2048.pem" 2048
fi

# Check if SSL certificates exist
if [ ! -f "/etc/ssl/nginx/nextcloud.crt" ] || [ ! -f "/etc/ssl/nginx/nextcloud.key" ]; then
	echo "SSL certificates not found. Exiting."
	exit 1
fi